### ISSUE TITLE
Vagrant pip fails and setup.py develop breaks environment

### ISSUE THREAD

**Issue by Osmose** [mozilla/dxr#394]
I don't quite have all the details but I wanted to leave some notes about ways I've broken the dev environment in a vagrant box:

1. `pip` or `peep.py` fails with:

   ``` 
   vagrant@vagrant-ubuntu-trusty-64 ~/dxr (python-inheritance*) $ sudo ./peep.py install -r    requirements.txt
   Traceback (most recent call last):
     File "./peep.py", line 66, in <module>
       import pip
     File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 11, in <module>
       from pip.vcs import git, mercurial, subversion, bazaar  # noqa
     File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
       from pip.download import path_to_url
     File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
       from requests.compat import IncompleteRead
   ImportError: cannot import name IncompleteRead
   ```

   (Note that even when this isn't breaking I can't install libraries without sudo, which is a bit weird.)

   `sudo easy_install -U pip` will fix this.

2. After re-running `sudo python setup.py develop` to reset the entry points after modifying them, attempting to run the tests fails:

   ```
   vagrant@vagrant-ubuntu-trusty-64 ~/dxr (python-inheritance*) $ nosetests --nologcapture dxr/plugins/python/tests
   E
   ======================================================================
   ERROR: Failure: ImportError (cannot import name ConnectionError)
   ----------------------------------------------------------------------
   Traceback (most recent call last):
     File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 414, in loadTestsFromName
       addr.filename, addr.module)
     File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
       return self.importFromDir(dir_path, fqname)
     File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
       mod = load_module(part_fqname, fh, filename, desc)
     File "/home/vagrant/dxr/dxr/plugins/python/__init__.py", line 5, in <module>
       from .indexers import mappings, TreeToIndex
     File "/home/vagrant/dxr/dxr/plugins/python/indexers.py", line 8, in <module>
       from dxr.build import file_contents, unignored
     File "/home/vagrant/dxr/dxr/build.py", line 21, in <module>
       from pyelasticsearch import (ElasticSearch, ElasticHttpNotFoundError,
     File "/usr/local/lib/python2.7/dist-packages/pyelasticsearch/__init__.py", line 3, in <module>
       from pyelasticsearch.client import ElasticSearch
     File "/usr/local/lib/python2.7/dist-packages/pyelasticsearch/client.py", line 18, in <module>
       from pyelasticsearch.exceptions import (ElasticHttpError,
     File "/usr/local/lib/python2.7/dist-packages/pyelasticsearch/exceptions.py", line 1, in <module>
       from urllib3.exceptions import TimeoutError as Timeout, ConnectionError
   ImportError: cannot import name ConnectionError
   
   ----------------------------------------------------------------------
   Ran 1 test in 0.002s
   
   FAILED (errors=1)
   ```

**Comment by Osmose** [comment]
I was able to fix 2 by running `rm -rf /usr/lib/python2.7/dist-packages/urllib3/` and using `pip` to install the latest urllib3. I have a feeling that `setup.py develop` is installing things to `/usr/lib` but `pip` is installing to `/usr/local/lib` and that `setup.py` has some requirements mixed up. But that's just a guess.

**Comment by erikrose** [comment]
There's a Debian-packaged version of requests that gets installed as a dependency of `python-pip`. (Either that version of pip was pre-vendor-lib, or Debian unwisely decided to un-vendor-libbify it when packaging.) It conflicts with everything, both directly and by means of its hoary version of urllib3. https://github.com/mozilla/dxr/commit/12c739a51075c0595b65686718aa2d0902c5c146 should take care of both of these errors (and move us on to the clang++ one).

**Comment by Osmose** [comment]
![f7k9yzezddtqc](https://cloud.githubusercontent.com/assets/193106/6517860/3a78339e-c354-11e4-99bf-1a2a30c5fe91.gif)
