### ISSUE TITLE
Npm errors when running make on Centos7

### ISSUE THREAD

**Issue by jlmarr10824** [mozilla/dxr#424]
This is from the es.zip snapshot downloaded yesterday.  I'll upload the logs shortly.

```
npm install
npm WARN package.json DXR@0.1.3 No repository field.

> DXR@0.1.3 preinstall /scratch/dxr-es-based/dxr-es
> lockdown

NPM Lockdown is here to check your dependencies!  Never fear!
npm WARN package.json DXR@0.1.3 No repository field.

> DXR@0.1.3 preinstall /scratch/dxr-es-based/dxr-es
> lockdown

npm ERR! Linux 3.10.0-123.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: phantomjs@'>=1.9.2-6 <1.10.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["1.9.7-1"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'uncss'
npm ERR! notarget 

npm ERR! Please include the following file with any support request:
npm ERR!     /scratch/dxr-es-based/dxr-es/npm-debug.log

npm ERR! Linux 3.10.0-123.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! DXR@0.1.3 preinstall: `lockdown`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the DXR@0.1.3 preinstall script 'lockdown'.
npm ERR! This is most likely a problem with the DXR package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     lockdown
npm ERR! You can get their info via:
npm ERR!     npm owner ls DXR
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /scratch/dxr-es-based/dxr-es/npm-debug.log
make: *** [node] Error 1
```

And then 

```
npm owner ls DXR
npm ERR! owner ls Couldn't get owner data DXR
npm ERR! Linux 3.10.0-123.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "owner" "ls" "DXR"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code E404

npm ERR! 404 Not Found: DXR
npm ERR! 404 
npm ERR! 404 'DXR' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /scratch/dxr-es-based/dxr-es/npm-debug.log
```

**Comment by jlmarr10824** [comment]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 warn package.json DXR@0.1.3 No repository field.
5 verbose install where, deps [ '/scratch/dxr-es-based/dxr-es',
5 verbose install   [ 'lockdown',
5 verbose install     'nunjucks',
5 verbose install     'grunt',
5 verbose install     'grunt-cli',
5 verbose install     'grunt-uncss',
5 verbose install     'grunt-processhtml',
5 verbose install     'grunt-contrib-jshint',
5 verbose install     'grunt-contrib-watch',
5 verbose install     'grunt-nunjucks' ] ]
6 verbose install where, peers [ '/scratch/dxr-es-based/dxr-es', [] ]
7 info preinstall DXR@0.1.3
8 verbose unsafe-perm in lifecycle true
9 info DXR@0.1.3 Failed to exec preinstall script
10 verbose stack Error: DXR@0.1.3 preinstall: `lockdown`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid DXR@0.1.3
12 verbose cwd /scratch/dxr-es-based/dxr-es
13 error Linux 3.10.0-123.el7.x86_64
14 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
15 error node v0.12.2
16 error npm  v2.7.4
17 error code ELIFECYCLE
18 error DXR@0.1.3 preinstall: `lockdown`
18 error Exit status 1
19 error Failed at the DXR@0.1.3 preinstall script 'lockdown'.
19 error This is most likely a problem with the DXR package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     lockdown
19 error You can get their info via:
19 error     npm owner ls DXR
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
```

**Comment by jlmarr10824** [comment]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'owner',
1 verbose cli   'ls',
1 verbose cli   'DXR' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 silly mapToRegistry name DXR
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry https://registry.npmjs.org/
7 silly mapToRegistry uri https://registry.npmjs.org/DXR
8 verbose request uri https://registry.npmjs.org/DXR
9 verbose request no auth needed
10 info attempt registry request try #1 at 9:13:09 AM
11 verbose request id c25095e756d29dba
12 http request GET https://registry.npmjs.org/DXR
13 http 404 https://registry.npmjs.org/DXR
14 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
14 verbose headers   'content-type': 'application/json',
14 verbose headers   'cache-control': 'max-age=0',
14 verbose headers   'content-length': '51',
14 verbose headers   'accept-ranges': 'bytes',
14 verbose headers   date: 'Tue, 09 Jun 2015 16:13:09 GMT',
14 verbose headers   via: '1.1 varnish',
14 verbose headers   age: '0',
14 verbose headers   connection: 'keep-alive',
14 verbose headers   'x-served-by': 'cache-lax1432-LAX',
14 verbose headers   'x-cache': 'MISS',
14 verbose headers   'x-cache-hits': '0',
14 verbose headers   'x-timer': 'S1433866389.369160,VS0,VE86' }
15 silly get cb [ 404,
15 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
15 silly get     'content-type': 'application/json',
15 silly get     'cache-control': 'max-age=0',
15 silly get     'content-length': '51',
15 silly get     'accept-ranges': 'bytes',
15 silly get     date: 'Tue, 09 Jun 2015 16:13:09 GMT',
15 silly get     via: '1.1 varnish',
15 silly get     age: '0',
15 silly get     connection: 'keep-alive',
15 silly get     'x-served-by': 'cache-lax1432-LAX',
15 silly get     'x-cache': 'MISS',
15 silly get     'x-cache-hits': '0',
15 silly get     'x-timer': 'S1433866389.369160,VS0,VE86' } ]
16 error owner ls Couldn't get owner data DXR
17 verbose stack Error: 404 Not Found: DXR
17 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:245:14)
17 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:170:14)
17 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:344:22)
17 verbose stack     at Request.emit (events.js:110:17)
17 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1239:14)
17 verbose stack     at Request.emit (events.js:129:20)
17 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1187:12)
17 verbose stack     at IncomingMessage.emit (events.js:129:20)
17 verbose stack     at _stream_readable.js:908:16
17 verbose stack     at process._tickCallback (node.js:355:11)
18 verbose statusCode 404
19 verbose pkgid DXR
20 verbose cwd /scratch/dxr-es-based/dxr-es
21 error Linux 3.10.0-123.el7.x86_64
22 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "owner" "ls" "DXR"
23 error node v0.12.2
24 error npm  v2.7.4
25 error code E404
26 error 404 Not Found: DXR
26 error 404
26 error 404 'DXR' is not in the npm registry.
26 error 404 You should bug the author to publish it (or use the name yourself!)
26 error 404
26 error 404 Note that you can also install from a
26 error 404 tarball, folder, http url, or git url.
27 verbose exit [ 1, true ]
```

**Comment by jlmarr10824** [comment]
Problem is solved in the latest snapshot.  Not sure when/how it was fixed.
