### ISSUE TITLE
Issues compiling firefox in docker

### ISSUE THREAD

**Issue by kleintom** [mozilla/dxr#511]
The makefile says "Presently, nothing outside the source checkout will be preserved on exit." and that's my experience, but the docs say to not put source to be compiled in ~/dxr - is there another way to do this?

Also, a new m-c install requires a `./mach bootstrap`, which asks for the root password (in lieu of sudo) to install what it needs - the docker password exists in the config files, but not in the docs.

I can take a shot at updating the docs (unless you'd rather), but just wanted to check on how this should actually be done.  Thanks!

**Comment by kleintom** [comment]
Also, I forgot - when I do `./mach bootstrap` from within docker I get:

Traceback (most recent call last):
  File "./mach", line 148, in <module>
    main(sys.argv[1:])
  File "./mach", line 76, in main
    mach = get_mach()
  File "./mach", line 67, in get_mach
    mach = check_and_get_mach(dir_path)
  File "./mach", line 42, in check_and_get_mach
    return load_mach(dir_path, mach_path)
  File "./mach", line 30, in load_mach
    return mach_bootstrap.bootstrap(dir_path)
  File "/home/dxr/dxr/ff/mozilla-central/build/mach_bootstrap.py", line 314, in bootstrap
    mach.load_commands_from_file(os.path.join(mozilla_dir, path))
  File "/home/dxr/dxr/ff/mozilla-central/python/mach/mach/main.py", line 258, in load_commands_from_file
    imp.load_source(module_name, path)
  File "/home/dxr/dxr/ff/mozilla-central/addon-sdk/mach_commands.py", line 13, in <module>
    from mozbuild.base import (
  File "/home/dxr/dxr/ff/mozilla-central/build/mach_bootstrap.py", line 340, in __call__
    module = self._original_import(name, globals, locals, fromlist, level)
  File "/home/dxr/dxr/ff/mozilla-central/python/mozbuild/mozbuild/base.py", line 17, in <module>
    from mach.mixin.process import ProcessExecutionMixin
  File "/home/dxr/dxr/ff/mozilla-central/build/mach_bootstrap.py", line 340, in __call__
    module = self._original_import(name, globals, locals, fromlist, level)
  File "/home/dxr/dxr/ff/mozilla-central/python/mach/mach/mixin/process.py", line 29, in <module>
    raise Exception('Could not detect environment shell!')
Exception: Could not detect environment shell!

Setting `export SHELL=/bin/bash` fixes it, but seems like that should be getting set somewhere else...

**Comment by erikrose** [comment]
If you pop onto #static on irc.mozilla.org, we can chat in realtime. I'm addressing some of your comments as we speak!

**Comment by erikrose** [comment]
f3c5db88e8d8d9a5f2394606871952d26a5dee36 adds a shiny new `/code` folder you can park your source in, and it won't evaporate when the container goes away.

**Comment by erikrose** [comment]
> Setting export SHELL=/bin/bash fixes it, but seems like that should be getting set somewhere else

tooling/docker/dev/Dockerfile would probably be a good place to set that, right in the same line where we set VIRTUAL_ENV and PATH.

**Comment by erikrose** [comment]
> I can take a shot at updating the docs

Have at it!

**Comment by asutherland** [comment]
What's the right way to address the need to run "./mach bootstrap" and "./mach mercurial-setup" every time "make shell" is invoked (since everything outside /code and ~/dxr is ephemeral)?  Should an additional make target and docker image layer-thing be created that are mozilla-central specific?  Is there something we can set in the docker image to make the root-level mutations be persistent?  (I am verrrrrry new to docker.  And I think comment 0 is sorta talking about this too.)  Thanks!

**Comment by erikrose** [comment]
@asutherland Yes, it is kind of a drag for packaged dependencies to evaporate all the time. I don't have a ready-made answer for you, unfortunately, but here are a couple ideas. Perhaps you can develop them further and share what you find. :-)

1. Add a noninteractive call to `mach bootstrap` and the mercurial setup to the Dockerfile, so the installed packages get cached. (Having to modify the Dockerfile is a bit ugly, though.)
2. Install the packages, then use the `docker commit` command to manually cache an image with the packages installed. I'm not sure how you then easily boot a container based on that image while tying it together with the other ones (es, dev, and venv). That would be something to look into.

**Comment by asutherland** [comment]
Thanks for the quick reply and suggestions!  I suppose a related question is whether there's a plan to move DXR to use taskcluster.  I think it uses Jenkins right now?  But since taskcluster is based on docker, there may be ways to align the two use-cases if that's something you're interested in.  (I say this to help guide my investigation rather than suggest scope creep for you, noting that I also have only limited taskcluster experience so it'd be more a question of what idioms I would attempt to naively imitate.)

**Comment by erikrose** [comment]
> Thanks for the quick reply and suggestions! I suppose a related question is whether there's a plan to move DXR to use taskcluster.

It's an option we've examined in the past, but we have no particular plans to take it. The main thing that killed it for us was its inability to fire off a task periodically, which seemed the easiest way to dual-trigger builds based on both the DXR repo and the repo being indexed. Also, TaskCluster runs on AWS, which is far away from our ES cluster. If we ever do move indexing to AWS, we'll have to move ES there as well or pay for 20GB of transfer every time we index a tree.

> I think it uses Jenkins right now?

Also, Jenkins gives us some nice UI for monitoring the success, progress, and logs of jobs for free.

> But since taskcluster is based on docker, there may be ways to align the two use-cases if that's something you're interested in.

I'm very interested in reusing the docker images Release Engineering builds Firefox within, since then we wouldn't have to deal with occasional dependency breakage. I don't remember why we didn't go in that direction. Perhaps @klibby remembers?

> (I say this to help guide my investigation rather than suggest scope creep for you, noting that I also have only limited taskcluster experience so it'd be more a question of what idioms I would attempt to naively imitate.)

Anyway, dockerfiles are not very good units of composability when you're talking about scribbling all over a filesystem. They do fine when you can root the interesting parts of a container in a single dir and mount them onto another, but things like global package installation that spew all over the disk don't compose. That's why we broke out DXR's dependency installation into shell scripts like set_up_ubuntu.sh: those are composable. Before Docker, we used to root the installed deps in a chroot using the `mock` tool so as not to interfere with the host OS's packages. I mention it in case it gives you any ideas.
