### ISSUE TITLE
Error when indexing basic test

### ISSUE THREAD

**Issue by AlexPham1988** [mozilla/dxr#625]
I have installed all necessary dependencies and make DXR successfully.

Then I set vitualenv and tried to index the basic test:

**(dxr_venv) alex@ubuntu:~/dxr/tests/test_basic$ dxr index

Starting tree 'code'.
Traceback (most recent call last):
  File "/home/alex/dxr_venv/bin/dxr", line 11, in <module>
    load_entry_point('dxr', 'console_scripts', 'dxr')()
  File "/home/alex/dxr/dxr/cli/__init__.py", line 29, in main
    return dxr.invoke(ctx)
  File "/home/alex/dxr_venv/local/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/alex/dxr_venv/local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/alex/dxr_venv/local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/alex/dxr/dxr/cli/index.py", line 26, in index
    index_and_deploy_tree(tree, verbose=verbose)
  File "/home/alex/dxr/dxr/build.py", line 61, in index_and_deploy_tree
    index_name = index_tree(tree, es, verbose=verbose)
  File "/home/alex/dxr/dxr/build.py", line 244, in index_tree
    {})
  File "/home/alex/dxr/dxr/es.py", line 110, in create_index_and_wait
    es.create_index(index, settings=settings)
  File "/home/alex/dxr_venv/local/lib/python2.7/site-packages/pyelasticsearch/client.py", line 93, in decorate
    return func(*args, query_params=query_params, **kwargs)
  File "/home/alex/dxr_venv/local/lib/python2.7/site-packages/pyelasticsearch/client.py", line 1033, in create_index
    query_params=query_params)
  File "/home/alex/dxr_venv/local/lib/python2.7/site-packages/pyelasticsearch/client.py", line 281, in send_request
    raise exc.info
urllib3.exceptions.ProtocolError: ('Connection aborted.', error(111, 'Connection refused'))**

May I know what is the problem here? I guess it come from Elasticsearch .

Thank you

Alex

**Comment by erikrose** [comment]
I strongly encourage you to use the included docker setup if you're having trouble. DXR's dependencies are hard to set up. That said, it looks like your ES isn't accepting connections. If you telnet to it (port 9200), does it answer?

**Comment by AlexPham1988** [comment]
Thanks Erik. I will try again then update if any other issue happens.
