### ISSUE TITLE
Advance searching in folder does not work

### ISSUE THREAD

**Issue by AlexPham1988** [mozilla/dxr#642]
Hi .  When I try to use function like "Limit search to folder" and "Exclude folder from search" ,

![untitled](https://cloud.githubusercontent.com/assets/13479939/23124379/99b4e602-f7a7-11e6-9b66-96c316013093.png)

ES showed an error message like this:

```
10.131.59.16 - - [20/Feb/2017 19:55:29] "GET /code/search?limit=100&redirect=false&q=1111%20path%3Afolder%2F&_=1487591728866 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/slowfs/lvg2/bpham/dxr_venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/slowfs/lvg2/bpham/dxr_venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/slowfs/lvg2/bpham/dxr_venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/slowfs/lvg2/bpham/dxr_venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/slowfs/lvg2/bpham/dxr_venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/slowfs/lvg2/bpham/dxr_venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/slowfs/lvg2/bpham/dxr_venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/slowfs/lvg2/bpham/dxr_venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/slowfs/lvg2/bpham/dxr2/dxr/app.py", line 143, in search
    return searcher(query, tree, query_text, offset, limit, config)
  File "/slowfs/lvg2/bpham/dxr2/dxr/app.py", line 176, in _search_json
    count_and_results = query.results(offset, limit)
  File "/slowfs/lvg2/bpham/dxr2/dxr/query.py", line 163, in results
    doc_type=LINE if is_line_query else FILE)['hits']
  File "/slowfs/lvg2/bpham/dxr_venv/lib/python2.7/site-packages/pyelasticsearch/client.py", line 93, in decorate
    return func(*args, query_params=query_params, **kwargs)
  File "/slowfs/lvg2/bpham/dxr_venv/lib/python2.7/site-packages/pyelasticsearch/client.py", line 859, in search
    return self._search_or_count('_search', query, **kwargs)
  File "/slowfs/lvg2/bpham/dxr_venv/lib/python2.7/site-packages/pyelasticsearch/client.py", line 836, in _search_or_count
    query_params=query_params)
  File "/slowfs/lvg2/bpham/dxr_venv/lib/python2.7/site-packages/pyelasticsearch/client.py", line 285, in send_request
    self._raise_exception(status, error_message)
  File "/slowfs/lvg2/bpham/dxr_venv/lib/python2.7/site-packages/pyelasticsearch/client.py", line 299, in _raise_exception
    raise error_class(status, error_message)
ElasticHttpError: (400, u'SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[SNIqVCR-QrysHxBIAvyaEQ][dxr_test_19_code_f46068be-f762-11e6-af31-002219596f9e][0]: SearchParseException[[dxr_test_19_code_f46068be-f762-11e6-af31-002219596f9e][0]: from[-1],size[-1],sort[<custom:"path": org.elasticsearch.index.fielddata.fieldcomparator.BytesRefFieldComparatorSource@3e023df4>,<custom:"number": org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource@5317dfa>]: Parse Failure [Failed to parse source [{"sort": ["path", "number"], "query": {"filtered": {"filter": {"and": [{"or": [{"query": {"match_phrase": {"content.trigrams_lower": "1111"}}}]}, {"or": [{"and": [{"query": {"match_phrase": {"path.trigrams_lower": "folder/"}}}, {"script": {"lang": "js", "params": {"pattern": "folder/", "flags": "i"}, "script": "(new RegExp(pattern, flags)).test(doc[\\"path\\"][0])"}}]}]}]}, "query": {"match_all": {}}}}, "from": 0, "size": 100}]]]; nested: ElasticsearchIllegalArgumentException[script_lang not supported [js]]; }{[SNIqVCR-QrysHxBIAvyaEQ][dxr_test_19_code_f46068be-f762-11e6-af31-002219596f9e][1]: SearchParseException[[dxr_test_19_code_f46068be-f762-11e6-af31-002219596f9e][1]: from[-1],size[-1],sort[<custom:"path": org.elasticsearch.index.fielddata.fieldcomparator.BytesRefFieldComparatorSource@bcdfe45>,<custom:"number": org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource@f06a11>]: Parse Failure [Failed to parse source [{"sort": ["path", "number"], "query": {"filtered": {"filter": {"and": [{"or": [{"query": {"match_phrase": {"content.trigrams_lower": "1111"}}}]}, {"or": [{"and": [{"query": {"match_phrase": {"path.trigrams_lower": "folder/"}}}, {"script": {"lang": "js", "params": {"pattern": "folder/", "flags": "i"}, "script": "(new RegExp(pattern, flags)).test(doc[\\"path\\"][0])"}}]}]}]}, "query": {"match_all": {}}}}, "from": 0, "size": 100}]]]; nested: ElasticsearchIllegalArgumentException[script_lang not supported [js]]; }{[SNIqVCR-QrysHxBIAvyaEQ][dxr_test_19_code_f46068be-f762-11e6-af31-002219596f9e][2]: SearchParseException[[dxr_test_19_code_f46068be-f762-11e6-af31-002219596f9e][2]: from[-1],size[-1],sort[<custom:"path": org.elasticsearch.index.fielddata.fieldcomparator.BytesRefFieldComparatorSource@5e9fcf2>,<custom:"number": org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource@44dd76e6>]: Parse Failure [Failed to parse source [{"sort": ["path", "number"], "query": {"filtered": {"filter": {"and": [{"or": [{"query": {"match_phrase": {"content.trigrams_lower": "1111"}}}]}, {"or": [{"and": [{"query": {"match_phrase": {"path.trigrams_lower": "folder/"}}}, {"script": {"lang": "js", "params": {"pattern": "folder/", "flags": "i"}, "script": "(new RegExp(pattern, flags)).test(doc[\\"path\\"][0])"}}]}]}]}, "query": {"match_all": {}}}}, "from": 0, "size": 100}]]]; nested: ElasticsearchIllegalArgumentException[script_lang not supported [js]]; }{[SNIqVCR-QrysHxBIAvyaEQ][dxr_test_19_code_f46068be-f762-11e6-af31-002219596f9e][3]: SearchParseException[[dxr_test_19_code_f46068be-f762-11e6-af31-002219596f9e][3]: from[-1],size[-1],sort[<custom:"path": org.elasticsearch.index.fielddata.fieldcomparator.BytesRefFieldComparatorSource@1e0f3bc1>,<custom:"number": org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource@7a1c0b51>]: Parse Failure [Failed to parse source [{"sort": ["path", "number"], "query": {"filtered": {"filter": {"and": [{"or": [{"query": {"match_phrase": {"content.trigrams_lower": "1111"}}}]}, {"or": [{"and": [{"query": {"match_phrase": {"path.trigrams_lower": "folder/"}}}, {"script": {"lang": "js", "params": {"pattern": "folder/", "flags": "i"}, "script": "(new RegExp(pattern, flags)).test(doc[\\"path\\"][0])"}}]}]}]}, "query": {"match_all": {}}}}, "from": 0, "size": 100}]]]; nested: ElasticsearchIllegalArgumentException[script_lang not supported [js]]; }{[SNIqVCR-QrysHxBIAvyaEQ][dxr_test_19_code_f46068be-f762-11e6-af31-002219596f9e][4]: SearchParseException[[dxr_test_19_code_f46068be-f762-11e6-af31-002219596f9e][4]: from[-1],size[-1],sort[<custom:"path": org.elasticsearch.index.fielddata.fieldcomparator.BytesRefFieldComparatorSource@2c8b4523>,<custom:"number": org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource@6b6813ad>]: Parse Failure [Failed to parse source [{"sort": ["path", "number"], "query": {"filtered": {"filter": {"and": [{"or": [{"query": {"match_phrase": {"content.trigrams_lower": "1111"}}}]}, {"or": [{"and": [{"query": {"match_phrase": {"path.trigrams_lower": "folder/"}}}, {"script": {"lang": "js", "params": {"pattern": "folder/", "flags": "i"}, "script": "(new RegExp(pattern, flags)).test(doc[\\"path\\"][0])"}}]}]}]}, "query": {"match_all": {}}}}, "from": 0, "size": 100}]]]; nested: ElasticsearchIllegalArgumentException[script_lang not supported [js]]; }]')
10.131.59.16 - - [20/Feb/2017 19:57:03] "GET /code/search?q=1111&_=1487591823462 HTTP/1.1" 200 -
```

Did I miss to enable some plugin while indexing ? I just use pygmentize for this tree.

Or my ES instance need to be updated ? Current version is 1.7.2

Thank you
Alex

**Comment by AlexPham1988** [comment]
This issue can be solved by:

1. Install `elasticsearch-lang-javascript`
2. Set `script.disable_dynamic: false`
